app/urls.py
from django.urls import path
from . import views


app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload, name='upload'),
    path('generate/', views.generate, name='generate'),
    path('group_gen/', views.group_generate, name='group-gen'),
    path('manage/', views.manage, name='manage'),
    path('delete_temp/<int:temp_id>/', views.delete_template, name='delete-template'),
    path('get_csv_all/', views.get_csv_all, name='get-csv-all'),
    path('get_csv/<int:temp_id>/', views.get_csv_byid, name='get-csv'),
    path('get_csv_multi/', views.get_csv_multi, name='get-csv-multi'),
    path('documents/', views.documents, name='documents'),
    path('download_doc/<int:doc_id>/<int:template>/', views.doc_download, name='doc-download'),
    path('download_all/', views.doc_download_all, name='download-all'),
    path('delete_doc/<int:doc_id>/', views.delete_document, name='delete-doc'),
    path('delete_all_docs/', views.delete_all_documents, name='delete-doc-all'),


]

generator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('staff/', include('staff.urls')),
    path('staff/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('login_staff/', views.login_staff, name='login'),
    path('registration/', views.register_staff, name='registration'),
    path('logout_staff/', views.user_logout, name='logout')

]

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en" >
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    <title>{% block title %} {% endblock %}</title>

    <style>
        .navbar{
            background-color: #131a14;
            color: inherit;
            color: white !important;
        }
        .nav-link{
            color: white !important;
            color: inherit;
        }

        body{
            background-color: #ffffff !important;
            /* background-color: #7f8780 !important; */

        }

        /* h1, h2, h3, h4, h5 {
            color: white
        } */

    </style>
</head>
<body>
    <div class=''>
      {% include 'app/navbar.html' %}
      <br>
      <div class="container-fluid">

        {% if messages %}
          {% for message in messages %}
          <div class="alert alert-primary alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>          
          {% endfor %}
        
        {% endif %}
      </div>


        <div class="px-xl-5">
          {% block body %}
          {% endblock body %}
        </div>

    </div>
</body>
</html>

app/templates/app/datafiles.html
{% extends 'app/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Excel{% endblock title %}

{% block body %}
    <h1>New Client's Data File</h1>
    <h3>Choose relevant templates to input new client's particulars</h3>
    <br>
    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <p><strong>{{ form.templates.label }}*</strong></p>   
            <div class="row pb-5">
                {% if form.templates %}
                    {% for template in form.templates %}
                    <div class="col-sm-3">
                        {{template}}
                    </div> 
                    {% endfor %}
                {% else %}
                    <p>No templates yet!</p>

                {% endif %}
            </div>

            <br>
            <input type="submit" class="btn btn-success" value="Click Here to Input Client's Particulars and Save Under Client's Name">
        </form>
    </div>

{% endblock body %}

app/templates/app/documents.html
{% extends 'app/base.html' %}

{% block title %}Documents{% endblock title %}



{% block body %}

    {% if not documents %}
        <h1>No files yet</h1>

    {% else %}
        <h1>Download Documents</h1>
        <br>
        <div class='row justify-content-md-center'>
        {% for document in documents %}
            <div class='col-sm-3'>
              <div class="card">
                  <div class="card-header">
                    {{ document.created_by }}
                  </div>
                  <div class="card-body">
                    <h5 class="card-title">{{ document.name }}</h5>
                    <p class="card-text">{{ document.timestamp }}</p>
                    <a href="{% url 'app:doc-download' document.id 0 %}" class="btn btn-primary">Download</a>
                    <a href="{% url 'app:delete-doc' document.id %}" class="btn btn-danger">Delete</a>
                  </div>
              </div>
            </div>
        {% endfor %}
        
        <a href="{% url 'app:download-all' %}" class="btn btn-primary mt-5">Download All</a>

        <a href="{% url 'app:delete-doc-all' %}" class="btn btn-danger mt-5">Delete All</a>

      </div>

    {% endif %}


{% endblock body %}

app/templates/app/generate.html
{% extends 'app/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Generate{% endblock title %}

{% block body %}
    <h1>Create Documents </h1>
    <h3>This Can Only Be Done After Client's Particulars Have Been Filled in the Excel Data File</h3>
    <br>
    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <p><strong>{{ form.templates.label }}*</strong></p>   
            <div class="row pb-5">
                {% if form.templates %}
                    {% for template in form.templates %}
                    <div class="col-sm-3">
                        {{template}}
                    </div> 
                    {% endfor %}
                {% else %}
                    <p>No templates yet!</p>

                {% endif %}
            </div>
            
            <div>
                <p><strong>{{ form.datafile.label }}*</strong></p>
                {{ form.datafile }}
            </div>

            <br>
            <input type="submit" class="btn btn-primary" value="Generate">
        </form>
    </div>

{% endblock body %}

app/templates/app/group_gen.html
{% extends 'app/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Generate{% endblock title %}

{% block body %}
    <h1>Create Documents </h1>
    <h3>This Can Only Be Done After Client's Particulars Have Been Filled in the Excel Data File</h3>
    <br>
    <a href="{% url 'app:generate' %}" class='btn btn-primary'>Individual Selection</a>
    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <p><strong>{{ form.label.label }}*</strong></p>   
            <div class="row pb-5">
                {% if form.label %}
                    {% for label in form.label %}
                    <div class="col-sm-3">
                        {{label}}
                    </div> 
                    {% endfor %}
                {% else %}
                    <p>No templates yet!</p>

                {% endif %}
            </div>
            
            <div>
                <p><strong>{{ form.datafile.label }}*</strong></p>
                {{ form.datafile }}
            </div>

            <br>
            <input type="submit" class="btn btn-primary" value="Generate">
        </form>
    </div>

{% endblock body %}

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block title %}Home{% endblock title %}


{% block body %}
    {% if user.is_authenticated %}
        <h2>Welcome, {{ user }}</h2>

    {% else %}
        <h2>Please register or login</h2>
    
    
    {% endif %}

{% endblock body %}

app/templates/app/manage.html
{% extends 'app/base.html' %}

{% block title %}{% endblock title %}

{% block body %}
    {% if not templates %}

        <h1>No templates</h1>

            
    
    {% else %}
    <form action="">
        <div class='container-fluid'>
            <div class="card text mb-3">
                {% for template in templates %}
                    <div class="card-header">
                        <h3>{{ template.0 }}</h3>
                    </div>
                    <ol class="list-group-numbered">
                            {% for doc in template.1 %}
                            <br>
                            <li class="list-group-item">
                                <strong class="mx-5">{{ doc.name }} | {{ doc.timestamp }}</strong>
                                <a href="{% url 'app:get-csv' doc.id %}" class='btn btn-success pull-right'> Data File </a>
                                <a href="{% url 'app:doc-download' doc.id 1 %}" class="btn btn-primary">Download</a> 
                                {% if superuser %}
                                    <a href="{% url 'app:delete-template' doc.id %}" class='btn btn-danger pull-right'> Delete </a>
                                {% endif %}
                                

                            </li>      
                            {% endfor %}
                    </ol>
                {% endfor %}
            </div>
        </div>

        <div>
            <a href="{% url 'app:get-csv-all' %}" class="btn btn-success">Get General Data File</a>
        </div>
    </form>
    {% endif %}
    

{% endblock body %}

app/templates/app/navbar.html
<nav class="navbar navbar-expand-lg sticky-top " data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url "app:index"%}">Generator</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">

        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url "app:manage" %}">Manage Templates</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "app:upload" %}">Upload Template</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "app:get-csv-multi" %}">Datafiles</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "app:generate" %}">Create</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "app:documents" %}">Documents</a>
          </li>
            
          <li class="nav-item">
              <a class="nav-link" href="{% url "staff:logout" %}">Logout</a>
          </li>
          {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "staff:registration" %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "staff:login" %}">Login</a>
            </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>

app/templates/app/upload.html
{% extends 'app/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Upload{% endblock title %}

{% block body %}
    <h1>Upload Template</h1>
    <br>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        {{ form|crispy }}
        <br>
        <input type="submit" class='btn btn-success' value="Upload File">


    </form>
    <h2>If you don't see the group you want, add it below</h2>

    <form method="POST">
        {% csrf_token %}

        {{ labelform|crispy }}
        <input type="submit" class="btn btn-secondary" value="Add Group">
    </form>

    


{% endblock body %}